/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoanimaciones.gui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectoanimaciones.backed.manejadores.ManejadorEscritura;
import proyectoanimaciones.backed.manejadores.ManejadorPestaña;
import proyectoanimaciones.backed.objetos.Lienzo;

/**
 *
 * @author bryan
 */
public class DialogEditorGrafico extends javax.swing.JDialog {
    private final ManejadorPestaña manejadorPestañas = ManejadorPestaña.getInstancia();
    private final String pathLienzo;
    private final String pathColores;
    private final String pathTiempo;
    private final String pathPintar;
    private final List<Lienzo> lista;
    private final ManejadorEscritura manejadorEscritura = ManejadorEscritura.getInstancia();
    
    /**
     * Creates new form DialogEditorGrafico
     * @param parent Componente Principal
     * @param modal Mostrar
     * @param pathLienzo Path del Lienzo
     * @param pathColores Path del Colores
     * @param pathTiempo Path del Tiemo
     * @param pathPintar Path de Pintar
     * @param lista Lista de Lienzos
     */
    public DialogEditorGrafico(java.awt.Frame parent, boolean modal, String pathLienzo, String pathColores, String pathTiempo, String pathPintar, List<Lienzo> lista) {
        super(parent, modal);
        initComponents();
        this.pathLienzo = pathLienzo;
        this.pathColores = pathColores;
        this.pathPintar = pathPintar;
        this.pathTiempo = pathTiempo;
        this.lista = lista;
        addPestañas();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañas = new javax.swing.JTabbedPane();
        menu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuGuardar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuManualTecnico = new javax.swing.JMenuItem();
        menuManualUsuario = new javax.swing.JMenuItem();
        uml = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diseño");
        setMinimumSize(new java.awt.Dimension(867, 659));
        setSize(new java.awt.Dimension(867, 25));

        menuArchivo.setText("Archivo");

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuGuardar.setText("Guardar Cambios");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuGuardar);

        menu.add(menuArchivo);

        menuAyuda.setText("Ayuda");

        menuManualTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuManualTecnico.setText("Manual Técnico");
        menuManualTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualTecnicoActionPerformed(evt);
            }
        });
        menuAyuda.add(menuManualTecnico);

        menuManualUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuManualUsuario.setText("Manual Usuario");
        menuManualUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualUsuarioActionPerformed(evt);
            }
        });
        menuAyuda.add(menuManualUsuario);

        uml.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        uml.setText("Diagrama de Clases");
        uml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umlActionPerformed(evt);
            }
        });
        menuAyuda.add(uml);

        menuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAcercaDe.setText("Acerca de...");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAcercaDe);

        menu.add(menuAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañas, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañas, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        // TODO add your handling code here:
        if (pathColores != null && pathLienzo != null && pathPintar != null && pathTiempo != null) {
            System.out.println("Path: " + pathColores);
            System.out.println("Path: " + pathLienzo);
            System.out.println("Path: " + pathPintar);
            System.out.println("Path: " + pathTiempo);
            try {
                manejadorEscritura.escribirArchivoSalida(pathLienzo, manejadorEscritura.archivoLienzo(lista));
                manejadorEscritura.escribirArchivoSalida(pathColores, manejadorEscritura.archivoColores(lista));
                manejadorEscritura.escribirArchivoSalida(pathTiempo, manejadorEscritura.archivoTiempo(lista));
                manejadorEscritura.escribirArchivoSalida(pathPintar, manejadorEscritura.archivoPintar(lista));
                JOptionPane.showMessageDialog(this, "Se han guardado los cambios.");
            } catch (IOException ex) {
                Logger.getLogger(DialogEditorGrafico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        // TODO add your handling code here:
JOptionPane.showMessageDialog(null, 
 "                                         ANIMATIONS - GUATEMALA v1.0\n" +
"Animations - Guatemala, es un softaware dedicado a la creacion de animaciones con\n" +
"gráficos en 8 bits, con la caracteristica de que las imagenes son diseñadas en base \n" +
"a archivos de entrada.\n" +
"\nCopyright 2020" +
"\nEste softaware fue desarrollado por:" +
"\n(bryanrene-gomezgomez@cunoc.edu.gt) creado en:" +
"\n\t\tNetBeans IDE 8.2", "Acerca de...", JOptionPane.INFORMATION_MESSAGE);                                            
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void abrirPdf(String path){
        try {
            File archivo = new File(path);
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void menuManualTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualTecnicoActionPerformed
        // TODO add your handling code here:
        abrirPdf("./Manual Tecnico.pdf");
    }//GEN-LAST:event_menuManualTecnicoActionPerformed

    private void menuManualUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualUsuarioActionPerformed
        // TODO add your handling code here:
        abrirPdf("./Manual de Usuario.pdf");
    }//GEN-LAST:event_menuManualUsuarioActionPerformed

    private void umlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umlActionPerformed
        // TODO add your handling code here:
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("nohup display ./UML-ProyectoFinal.png");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_umlActionPerformed

    private void addPestañas() {
        lista.forEach((lienzo) -> {
            manejadorPestañas.addNuevaPestaña(pestañas, lienzo.getNombre(), lienzo, this);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuManualTecnico;
    private javax.swing.JMenuItem menuManualUsuario;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JMenuItem uml;
    // End of variables declaration//GEN-END:variables
}
