
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectoanimaciones.backed.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 5;
  public static final int Duracion = 21;
  public static final int Coma = 24;
  public static final int Hexadecimal = 35;
  public static final int Colores = 3;
  public static final int Tiempos = 4;
  public static final int Id = 20;
  public static final int LlaveC = 28;
  public static final int LlaveA = 27;
  public static final int TamañoR = 11;
  public static final int NombreLienzo = 34;
  public static final int Lienzos = 2;
  public static final int Blue = 9;
  public static final int DimensionY = 15;
  public static final int DimensionX = 14;
  public static final int Cuadro = 13;
  public static final int Imagenes = 19;
  public static final int Hex = 16;
  public static final int Fin = 18;
  public static final int Red = 8;
  public static final int EOF = 0;
  public static final int DosPuntos = 23;
  public static final int Tamaño = 12;
  public static final int CorcheteC = 26;
  public static final int error = 1;
  public static final int CorcheteA = 25;
  public static final int Green = 10;
  public static final int Tipo = 6;
  public static final int Extension = 33;
  public static final int Inicio = 17;
  public static final int NumeroRGB_2 = 31;
  public static final int Identificador = 29;
  public static final int NumeroRGB_1 = 30;
  public static final int Fondo = 7;
  public static final int Numero = 32;
  public static final int Comillas = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Lienzos",
  "Colores",
  "Tiempos",
  "Nombre",
  "Tipo",
  "Fondo",
  "Red",
  "Blue",
  "Green",
  "TamañoR",
  "Tamaño",
  "Cuadro",
  "DimensionX",
  "DimensionY",
  "Hex",
  "Inicio",
  "Fin",
  "Imagenes",
  "Id",
  "Duracion",
  "Comillas",
  "DosPuntos",
  "Coma",
  "CorcheteA",
  "CorcheteC",
  "LlaveA",
  "LlaveC",
  "Identificador",
  "NumeroRGB_1",
  "NumeroRGB_2",
  "Numero",
  "Extension",
  "NombreLienzo",
  "Hexadecimal"
  };
}

