
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectoanimaciones.backed.analizador.pintar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 14;
  public static final int True = 5;
  public static final int MenorMayor = 21;
  public static final int PuntoComa = 29;
  public static final int Coma = 28;
  public static final int If = 10;
  public static final int IgualIgual = 20;
  public static final int LlaveC = 33;
  public static final int LlaveA = 32;
  public static final int Menos = 25;
  public static final int Mas = 24;
  public static final int Menor = 15;
  public static final int Else = 11;
  public static final int Por = 26;
  public static final int Mayor = 16;
  public static final int Punto = 22;
  public static final int While = 12;
  public static final int Pintar = 4;
  public static final int Int = 7;
  public static final int Cadena = 37;
  public static final int EOF = 0;
  public static final int And = 13;
  public static final int CorcheteC = 31;
  public static final int error = 1;
  public static final int CorcheteA = 30;
  public static final int False = 6;
  public static final int Div = 27;
  public static final int Vars = 2;
  public static final int MenorIgual = 18;
  public static final int Instrucciones = 3;
  public static final int String = 8;
  public static final int Identificador = 36;
  public static final int MayorIgual = 19;
  public static final int ParentesisC = 35;
  public static final int Boolean = 9;
  public static final int ParentesisA = 34;
  public static final int Numero = 23;
  public static final int Igual = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Vars",
  "Instrucciones",
  "Pintar",
  "True",
  "False",
  "Int",
  "String",
  "Boolean",
  "If",
  "Else",
  "While",
  "And",
  "Or",
  "Menor",
  "Mayor",
  "Igual",
  "MenorIgual",
  "MayorIgual",
  "IgualIgual",
  "MenorMayor",
  "Punto",
  "Numero",
  "Mas",
  "Menos",
  "Por",
  "Div",
  "Coma",
  "PuntoComa",
  "CorcheteA",
  "CorcheteC",
  "LlaveA",
  "LlaveC",
  "ParentesisA",
  "ParentesisC",
  "Identificador",
  "Cadena"
  };
}

